# -*- coding: utf-8 -*-
"""diabetespredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gm5ZG9AtWED1gtA_Yl4Pv0ETRQi-AHWj
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
data=pd.read_csv('/content/diabetes.csv')
X=data.drop(columns='Outcome',axis=1)
Y=data['Outcome']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=3,stratify=Y)
model=LogisticRegression(max_iter=1000)
model.fit(X_train,Y_train)
prediction=model.predict(X_test)
accuracy=accuracy_score(prediction,Y_test)
print(accuracy*100)